name: Build and push container
on:
    workflow_dispatch:
        inputs:
            push_image:
                description: 'Push image to registry'
                type: boolean
                default: false
                required: true

permissions:
    contents: read
    packages: write

jobs:
    build_and_push:
        if: |
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'workflow_run' && 
             github.event.workflow_run.conclusion == 'success' && 
             needs.check_release.outputs.new_release == 'true')
        name: Build image & push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get package name
              id: package-name
              run: |
                  echo "PACKAGE_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

            - name: Get package version
              id: package-version
              run: |
                  echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: Set lower case owner name
              run: |
                  echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                  OWNER: '${{ github.repository_owner }}'

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: >-
                      ${{
                        github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' ||
                        github.event_name == 'workflow_dispatch' && inputs.push_image
                      }}
                  build-args: |
                      VITE_EMAILJS_PUBLIC_KEY=${{secrets.VITE_EMAILJS_PUBLIC_KEY}}
                      VITE_GMAIL_SERVICE_ID=${{secrets.VITE_GMAIL_SERVICE_ID}}
                      VITE_EMAIL_TEMPLATE_ID=${{secrets.VITE_EMAIL_TEMPLATE_ID}}
                  tags: |
                      ghcr.io/${{ env.OWNER_LC }}/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
