name: Deploy

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Choose version to deploy (leave empty to deploy latest)'
                required: false
                type: string
                default: ''
    workflow_run:
        workflows: ['Release']
        types:
            - completed
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
        steps:
            - name: Set lower case owner name
              run: |
                  echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                  OWNER: '${{ github.repository_owner }}'

            - name: Set latest tag
              id: latest_version
              if: github.event.inputs.tag == ''
              run: |
                  echo "TAG=$(gh api repos/Krupenz/kkrupa-landing-page/tags | jq -r ".[0].name[1:]")" >> $GITHUB_ENV

            - name: Set specific tag
              if: github.event.inputs.tag != ''
              run: |
                  echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

            - name: Deploy through SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker compose down
                      sed -i "s/^VERSION=.*/VERSION=${TAG}/" .env
                      docker compose up -d
