name: Build and Store Docker Image

on:
    push:
        branches: [dockerize-ci]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get package name
              id: package-name
              run: |
                  echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

            - name: Get package version
              id: package-version
              run: |
                  echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ github.repository_owner }}/${{ steps.package-name.outputs.NAME }}:${{ steps.package-version.outputs.VERSION }}
