name: Build and Store Docker Image

on:
    push:
        branches: [dockerize-ci]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Get package name
              id: package-name
              run: |
                  echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

            - name: Get package version
              id: package-version
              run: |
                  echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and export
              uses: docker/build-push-action@v6
              with:
                  context: .
                  tags: |
                      ${{ steps.package-name.outputs.NAME }}:${{ steps.package-version.outputs.VERSION }}
                  outputs: type=docker,dest=/tmp/docker-image.tar

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: docker-image
                  path: /tmp/docker-image.tar
                  retention-days: 7
