name: 'Continous deployment on push to main'

on:
    push:
        branches: ['main']

permissions:
    contents: write
    packages: write

jobs:
    validate:
        uses: ./.github/workflows/reusable-validate.yml
    release:
        needs: validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/workflows/reusable-release.yml
            - name: print outputs
              run: echo "$OUTPUTS"
              shell: bash
              env:
                  OUTPUTS: ${{ toJSON(steps.release.outputs) }}
    build_and_push:
        if: needs.release.outputs.is_new_release == 'true'
        needs: release
        uses: ./.github/workflows/reusable-build.yml
        with:
            push_image: true
    deploy:
        needs: build_and_push
        uses: ./.github/workflows/reusable-deploy.yml
        secrets: inherit
        with:
            tag: ${{ needs.release.outputs.released_version }}
