name: Release
on:
    workflow_run:
        workflows: ['Validate']
        types:
            - completed
        branches:
            - main

permissions:
    contents: read

jobs:
    release:
        name: Release
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        outputs:
            commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: npm clean-install

            - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
              run: npm audit signatures

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release

            - name: Get commit hash
              id: get-commit-hash
              run: echo "commit_hash=$(git rev-parse HEAD)" >>
    build_and_push:
        needs: release
        name: Build image & push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ needs.release.outputs.commit_hash }}

            - name: Get package name
              id: package-name
              run: |
                  echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

            - name: Get package version
              id: package-version
              run: |
                  echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: set lower case owner name
              run: |
                  echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                  OWNER: '${{ github.repository_owner }}'

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ env.OWNER_LC }}/${{ steps.package-name.outputs.NAME }}:${{ steps.package-version.outputs.VERSION }}
