name: Reusable Validate
on: workflow_call
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
    install:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: npm ci
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: npm run build
    static-code-analysis:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
            - name: Run ESLint
              run: npm run lint
