name: '[Reusable] Build container'
on:
    workflow_call:
        inputs:
            push_image:
                description: 'Push image to registry'
                type: boolean
                default: false
                required: true
    workflow_dispatch:
        inputs:
            push_image:
                description: 'Push image to registry'
                type: boolean
                default: false
                required: true

permissions:
    contents: read
    packages: write

jobs:
    build:
        name: Build image & push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: Get package name
              id: package-name
              run: |
                  echo "PACKAGE_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

            - name: Get package version
              id: package-version
              run: |
                  echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: Set lower case owner name
              run: |
                  echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                  OWNER: '${{ github.repository_owner }}'

            - name: Set image tag
              run: |
                  if [[ "${{ github.ref_name }}" == "main" ]]; then
                      echo "IMAGE_TAG=${{ env.PACKAGE_VERSION }}" >> $GITHUB_ENV
                  else
                      echo "IMAGE_TAG=${{ env.PACKAGE_VERSION }}-dev.${{ github.run_number }}" >> $GITHUB_ENV
                  fi
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: ${{ inputs.push_image }}
                  tags: |
                      ghcr.io/${{ env.OWNER_LC }}/${{ env.PACKAGE_NAME }}:${{ env.IMAGE_TAG }}
