name: Reusable Validate
on: workflow_call
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-node
            - name: Install dependencies
              run: npm ci
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-node
            - name: Build
              run: npm run build
    static-code-analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-node
            - name: Run ESLint
              run: npm run lint
