name: '[Reusable] Release'
on: workflow_call
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: Install dependencies
              run: npm clean-install
            - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
              run: npm audit signatures
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
            - name: Get commit hash
              id: get-commit-hash
              run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    check_release:
        needs: release
        runs-on: ubuntu-latest
        outputs:
            is_new_release: ${{ steps.verify-release.outputs.is_new_release }}
            released_version: ${{ steps.get-new-version.outputs.released_version }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: Verify if new release was created
              id: verify-release
              run: |
                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
                  PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "none")
                  if [ "$LATEST_TAG" != "$PREVIOUS_TAG" ]; then
                  echo "is_new_release=true" >> $GITHUB_OUTPUT
                  echo "released_version=$LATEST_TAG" >> $GITHUB_OUTPUT
                  else
                  echo "is_new_release=false" >> $GITHUB_OUTPUT
                  fi
