name: Reusable Validate
on: workflow_call
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: Build
              run: npm run build
    static-code-analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: Run ESLint
              run: npm run lint
